opt_in_rules:
- vertical_whitespace_opening_braces
- vertical_whitespace_closing_braces
- vertical_parameter_alignment_on_call
- vertical_parameter_alignment

disabled_rules:
- trailing_whitespace
- unused_setter_value

included:

excluded:
- Pods
- LibrariesPractice/Application
